# -*- coding: utf-8 -*-
"""5-powerpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/JSJeong-me/RPA-2023/blob/main/pywinauto/5-powerpoint.ipynb
"""

# !pip install python-pptx
import collections 
import collections.abc
from PIL import Image
from pptx import Presentation

prs = Presentation()
bullet_slide_layout = prs.slide_layouts[1]

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes

title_shape = shapes.title
body_shape = shapes.placeholders[1]

title_shape.text = '6월 19일 전력 수요 예측'

# tf = body_shape.text_frame
# tf.text = 'Find the bullet slide layout'

# p = tf.add_paragraph()
# p.text = 'Use _TextFrame.text for first bullet'
# p.level = 1

# p = tf.add_paragraph()
# p.text = 'Use _TextFrame.add_paragraph() for subsequent bullets'
# p.level = 2

# prs.save('test.pptx')

# from pptx import Presentation
from pptx.util import Inches

img_path = 'fig1.png'

# prs = Presentation()
# blank_slide_layout = prs.slide_layouts[6]
# slide = prs.slides.add_slide(blank_slide_layout)

left = Inches(0)
top = Inches(1.5)
# pic = slide.shapes.add_picture(img_path, left, top)

# left = Inches(5)
width = Inches(4.5)
height = Inches(5.5)
pic = slide.shapes.add_picture(img_path, left, top, height=height)

prs.save('test.pptx')